config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/blogs' => 'blogs#index'
  # get '/blogs/new' => 'blogs#new'
  # post '/blogs' => 'blogs#create'
  # get '/blogs/:id' => 'blogs#show' , as:'blog'
  # get '/blogs/:id/edit' => 'blogs#edit', as:'edit_blog'
  # routes.rbで定義したルーティングはターミナルでrake routesと打つと確認できる
  # delete '/blogs/:id' => 'blogs#destroy', as: 'destroy_blog'
  root "blogs#index"
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	attachment :blog_image
	# refileでは、定義したカラム名から_idを抜いたものをattachmentというメソッドに定義する
	# 以降、blog_imageというカラムとして扱っていく
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
	end
	def new
		@blog = Blog.new
		# @つけると、対応するviewで使える
		# ブログモデルと紐付いた（データを入れる）空の箱を定義
		# インスタンスと言う。
	end
	def create
		blog = Blog.new(blog_params)
		# ビューから送られてきたデータをblogという空き箱に入れている
		blog.save
		redirect_to "/blogs"
		# 他のviewに移動するメソッド
		# binding.pry
		# コンソールに入りたい場所でbinding.pryを記述
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		blog = Blog.find(params[:id])
		blog.update(blog_params)
		redirect_to "/blogs/#{blog.id}"
		# redirect_to blog_path(blog.id)
		# rake routesで確認できるprefixを使用
	end

	def destroy
		blog = Blog.find(params[:id])
		blog.destroy
		redirect_to blogs_path
	end

	private
		def blog_params
			params.require(:blog).permit(:title, :body, :category, :blog_image)
			# viewから送信されたデータはparamsというメソッドの中に入っている
			# ストロングパラメータは、セキュリティを強固にしているもの
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@blog) do |f| %>
	<h4>タイトル</h4>
	<%= f.text_field :title %>
	<h4>本文</h4>
	<%= f.text_area :body %>
	<h4>カテゴリー</h4>
	<%= f.text_field :category%>
	<%= f.submit '保存' %>
	<h2>画像</h2>
	<%= f.attachment_field :blog_image %>
	<%= f.submit '投稿' %>
<% end %>

app/views/blogs/index.html.erb
<header>
    <h1 class="headline">
      <a href="#">CARAVAN</a>
    </h1>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </header>

  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a href="#">Home</a>
      </li>
      <li class="nav-list-item">About</li>
      <li class="nav-list-item">Topic</li>
    </ul>
  </nav>

  <div class="main-visual">
    <div class="main-visual-content">
      <p class="main-visual-text">
        The world is a book<br>
        and those who do not travel<br>
        read only one page.
      </p>
      <p class="main-visual-name">
        St. Augustine
      </p>
    </div>
  </div>

  <main class="clearfix">
    <section class="blog">
      <h2 class="blog-headline">Recent Blogs</h2>
      <div class="blog-box">
        <!-- 第三回でここから書き換える -->
        <% @blogs.each do |blog| %>
        <!-- =を外すと画面に出力されなくなる -->
        <div class="blog-item clearfix">
          <%= attachment_image_tag blog, :blog_image, class: "blog-image" %>
          <!-- <%= image_tag "img/forest.jpg",class: "blog-image"  %> -->
          <!-- <img class="blog-image" src="img/forest.jpg"> -->
          <section class="blog-text">
            <h3 class="blog-text-headline">
              <!-- ここにタイトルを表示 -->
              <%= link_to blog.title, "/blogs/#{blog.id}" %>
              <!-- インスタンス.カラム名 -->
            </h3>
            <p class="blog-date">
              <!-- 日付 -->
              <%= blog.created_at %>
            </p>
            <span class="category">
              <!-- カテゴリーを表示 -->
              <%= blog.category %>
            </span>
          </section>
        </div>
        <% end %>
        <!-- ここまで -->
      </div>
      <div class="pagination">
        <p><<</p>
        <p><</p>
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>></p>
        <p>>></p>
      </div>
    </section>
    <div class="sidebar">
      <section class="popular">
        <h2 class="sidebar-headline">Popular</h2>
        <div class="sidebar-contents">
          <p class="popular-text">To solve old problems,<br>study new species</p>
          <p class="popular-text">Why Earth may someday<br>look like Mars</p>
          <p class="popular-text">What will humans look<br>like in 100 years?</p>
          <p class="popular-text">How to grow a forest<br>in your backyard</p>
          <p class="popular-text">How humans could evolve<br>to survive in space</p>
        </div>
      </section>
      <section class="instagram">
        <h2 class="instagram-headline">Instagram</h2>
        <div class="sidebar-contents clearfix">
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
        </div>
      </section>
      <section class="categories">
        <h2 class="categories-headline">Categories</h2>
        <div class="sidebar-contents">
          <p class="categories-text">Technology(15)</p>
          <p class="categories-text">Business(23)</p>
          <p class="categories-text">Entertainment(12)</p>
          <p class="categories-text">Nature(32)</p>
          <p class="categories-text">Education(9)</p>
          <p class="categories-text">Adventure(23)</p>
          <p class="categories-text">Communication(14)</p>
        </div>
      </section>
    </div>
  </main>

  <footer>
    <p class="footer-text">© All rights recerved by Infratop.Inc.</p>
  </footer>

app/views/blogs/new.html.erb
<h2>新規投稿</h2>

<%= form_for(@blog) do |f| %>
<p>タイトル</p>
	<%= f.text_field :title %>
<p>本文</p>
	<%= f.text_area :body %>
<p>カテゴリー</p>
	<%= f.text_field :category %>
	<%= f.submit %>
<h2>画像</h2>
	<%= f.attachment_field :blog_image %>
	<%= f.submit '投稿' %>
<% end -%>

app/views/blogs/show.html.erb
<header>
    <h1 class="headline">
      <%= link_to "CARAVAN", blogs_path %>
    </h1>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </header>

  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a href="#">Home</a>
      </li>
      <li class="nav-list-item">About</li>
      <li class="nav-list-item">Topic</li>
    </ul>
  </nav>

  <div class="main-visual">
      <div class="main-visual-content">
        <p class="main-visual-text">
          The world is a book<br>
          and those who do not travel<br>
          read only one page.
        </p>
        <p class="main-visual-name">
          St. Augustine
        </p>
      </div>
    </div>

  <main class="clearfix">
    <section class="single-blog">
      <h2 class="blog-headline">Blog</h2>
      <section class="blog-box">
            <h3 class="blog-box-headline">
             <!-- タイトル -->
             <%= @blog.title %>
            </h3>

            <div class="blog-box-content">
              <p class="category">
              <!-- カテゴリー -->
              <%= @blog.category %>
              </p>
              <p class="blog-date">
              <!-- 日付 -->
              <%= @blog.created_at %>
          </p>
            </div>

              <div class="single_image">
                <%= attachment_image_tag @blog, :blog_image %>
              </div>
              <p class="single_text">
            <!-- 本文 -->
            <h1>本文</h1>
            <%= @blog.body %>
              </p>

            <%= link_to "編集", edit_blog_path(@blog), method: :get %>
              <!--link_toメソッドはデフォルトでHTTPメソッドがgetなので、定義しなくてもよい -->
              <!-- form_forは、 -->
            <%= link_to "削除", edit_blog_path(@blog), method: :delete %>

          <div class="author_case clearfix">
            <div class="author_image"></div>
              <div class="author_box">
                <p class="author_name">By JOHN SMITH / Photographer</p>
                <p class="author-text">His black and white landscapes, often captured at times<br>of the day and night when the light is fleeting, or in poor<br>weather conditions, such as rain, fog, or snow, are<br>reminiscent of the calm in a storm all with an ethereal<br>quality.
                </p>
              </div>
            </div>
        </section>
      </section>

    <div class="sidebar">
      <section class="popular">
        <h2 class="sidebar-headline">Popular</h2>
        <div class="sidebar-contents">
          <p class="popular-text">To solve old problems,<br>study new species</p>
          <p class="popular-text">Why Earth may someday<br>look like Mars</p>
          <p class="popular-text">What will humans look<br>like in 100 years?</p>
          <p class="popular-text">How to grow a forest<br>in your backyard</p>
          <p class="popular-text">How humans could evolve<br>to survive in space</p>
        </div>
      </section>
      <section class="instagram">
        <h2 class="instagram-headline">Instagram</h2>
        <div class="sidebar-contents clearfix">
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
        </div>
      </section>
      <section class="categories">
        <h2 class="categories-headline">Categories</h2>
        <div class="sidebar-contents">
          <p class="categories-text">Technology(15)</p>
          <p class="categories-text">Business(23)</p>
          <p class="categories-text">Entertainment(12)</p>
          <p class="categories-text">Nature(32)</p>
          <p class="categories-text">Education(9)</p>
          <p class="categories-text">Adventure(23)</p>
          <p class="categories-text">Communication(14)</p>
        </div>
      </section>
    </div>
  </main>
  <footer>
    <p class="footer-text">© All rights recerved by Infratop.Inc.</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caravan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>